### ISSUE TITLE
LAN

### ISSUE THREAD

**Issue by GruneBrentPieters** [bwp91/homebridge-ewelink-sonoff#9]
Please could you include the LAN feature

**Comment by bwp91** [comment]
Hi @GruneBrentPieters 
I have no experience with LAN mode from an implementation point of view.
However nothing is a “no” for me :)
I am aware of another package for sonoff devices that does support lan mode if you’re looking for something immediate:
https://github.com/dhutchison/homebridge-ewelink
As i said since it’s not a “no”, not going to close this issue as it is something i’d like to implement, just so far no one has requested it.
Gimme a couple of days and i’ll give you an update.
Ben

**Comment by GruneBrentPieters** [comment]
Hi

I would love to help, any way I can. Started with Homebridge and Sonoff ages ago, and now have basic switches, light switches, a bridge, dw1, dw2, POW2 and two DC powered units opening the garage. 

Happy to be a guinea pig, and help with documentation?

**Comment by bwp91** [comment]
Your help would be ideal would you be happy to send me an email? (address in next comment)

**Comment by bwp91** [comment]
bwp91@icloud.com

**Comment by GruneBrentPieters** [comment]
Here you go Sent from Mail for Windows 10 From: BenSent: Sunday, 19 July 2020 20:46To: bwp91/homebridge-ewelink-sonoffCc: GruneBrentPieters; MentionSubject: Re: [bwp91/homebridge-ewelink-sonoff] LAN (#9) bwp91@icloud.com—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bwp91** [comment]
@GruneBrentPieters thanks! tho all i’d need is your email address 🙈

**Comment by bwp91** [comment]
Closing this issue as:
- I am in the process of implementing LAN mode.
